commit_message: '%language% translation for %original_file_name% [skip ci]'
append_commit_message: 
files:
  - source: /localization/rssguard_en.ts
    translation: /localization/rssguard_%osx_locale%.ts
